"""
SoulX-Flash Lite service (image + speech  ->  talking avatar video).

    avatar image  +  generated speech
                  |
        SoulX-Flash Lite  (on your RunPod Serverless endpoint)
                  |
           talking avatar video (MP4)

=======================================================================
WORKER-SPECIFIC CONFIGURATION - THIS IS THE FILE YOU EDIT
=======================================================================
As with CosyVoice, the request and response field names come from the
RunPod worker handler you deploy, not from a public API. Nothing below is
presented as an official documented parameter.

When you have your worker's schema, change:

    1. build_payload()  -> the "input" object your handler expects
    2. VIDEO_*_KEYS     -> where the MP4 comes back
    3. RESOLUTION_MAP   -> the resolutions your worker actually supports

If your worker cannot do 1080p, remove it from ALLOWED_QUALITIES in .env so
the API rejects it up front instead of quietly returning a smaller video.
=======================================================================
"""

from __future__ import annotations

import base64
import logging
from typing import Any, Awaitable, Callable

from app.config import settings
from app.services import runpod_service
from app.utils.media_utils import result_to_bytes
from app.utils.validation import PipelineError

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------
# 1. REQUEST ADAPTER - edit to match your worker
# ---------------------------------------------------------------------

VIDEO_BASE64_KEYS = ("video_base64", "video", "video_b64", "base64", "mp4_base64")
VIDEO_URL_KEYS = ("video_url", "url", "output_url", "file_url", "s3_url")

OUTPUT_EXTENSION = ".mp4"

# Quality label -> pixel height the worker understands.
RESOLUTION_MAP: dict[str, int] = {
    "480p": 480,
    "720p": 720,
    "1080p": 1080,
}


def build_payload(
    *,
    image_base64: str,
    image_format: str,
    audio_base64: str,
    audio_format: str,
    quality: str,
) -> dict[str, Any]:
    """Build the "input" object sent to the SoulX-Flash Lite RunPod worker."""
    height = RESOLUTION_MAP.get(quality)
    if height is None:
        raise PipelineError(
            f"The avatar worker is not configured for {quality}. "
            "Pick a different quality or update RESOLUTION_MAP."
        )

    return {
        # Source image of the person, inline as base64.
        "image": image_base64,
        "image_format": image_format.lstrip("."),
        # The speech generated by CosyVoice in the previous step.
        "audio": audio_base64,
        "audio_format": audio_format.lstrip("."),
        # Output settings.
        "resolution": height,
        "quality": quality,
        "fps": 25,
    }


# ---------------------------------------------------------------------
# 2. SERVICE FUNCTION - used by the pipeline
# ---------------------------------------------------------------------


async def generate_avatar_video(
    *,
    image_bytes: bytes,
    image_format: str,
    audio_bytes: bytes,
    audio_format: str,
    quality: str,
    on_job_id: Callable[[str], Awaitable[None]] | None = None,
    on_poll: Callable[[str, float], Awaitable[None]] | None = None,
) -> tuple[bytes, str]:
    """
    Run SoulX-Flash Lite on RunPod and return (video_bytes, extension).

    The worker is responsible for lip-sync, facial expressions and muxing the
    audio into the MP4. This function only moves data in and out.
    """
    payload = build_payload(
        image_base64=base64.b64encode(image_bytes).decode("ascii"),
        image_format=image_format,
        audio_base64=base64.b64encode(audio_bytes).decode("ascii"),
        audio_format=audio_format,
        quality=quality,
    )

    logger.info("Starting SoulX-Flash Lite job at %s", quality)

    output = await runpod_service.run_and_wait(
        settings.SOULXFLASH_ENDPOINT_ID,
        payload,
        on_job_id=on_job_id,
        on_poll=on_poll,
    )

    video_bytes = await result_to_bytes(
        output,
        base64_keys=VIDEO_BASE64_KEYS,
        url_keys=VIDEO_URL_KEYS,
        what="video",
    )
    logger.info("SoulX-Flash Lite returned %d bytes of video", len(video_bytes))
    return video_bytes, OUTPUT_EXTENSION
